const express=require('express');

const mongoose=require('mongoose')

const orderSchema=new mongoose.Schema({
    shippingInfo:{
        name:{
            type:String,
            required:true
        },
        address:{
            type:String,
            required:true
        },
        landmark:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pinCode:{
            type:Number,
            required:true
        },
        phoneNo:{
            type:Number,
            required:true
        }
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            images:[
                {
                    public_id:{
                        type:String,
                        required:true
                    },
                    url:{
                        type:String,
                        required:true
                    }
                }
            ],
            product_id:{
                type:mongoose.Schema.ObjectId,
                ref:'Product',
                required:true
            }
        }
    ],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:'User',
        required:true
    },
    paymentInfo:{
        number:{
            type:String,
            required:true
        },
        cvv:{
            type:String,
            required:true
        },
        expiryDate:{
            type:String,
            required:true
        },
        id:{
            type:String,
            required:true,
        },
        status:{
            type:String,
            required:true
        }
    },
    paidAt:{
        type:Date,
        required:true
    },
    itemsPrice:{
        type:Number,
        default:0
    },
    taxPrice:{
        type:Number,
        default:0
    },
    shippingPrice:{
        type:Number,
        required:true
    },
    totalPrice:{
        type:Number,
        required:true
    },
    orderStatus:{
        type:String,
        required:true,
        default:'Processing'
    },
    deliveredAt:Date,
    createdAt:{
        type:Date,
        default:Date.now
    }
})

module.exports=mongoose.model("Order",orderSchema);